join-message:
  message: "<red>Welcome to the server!"
  title:
    title: "<red>Welcome to the server! (title)"
    sub-title: "<purple>We hope you'll like it here."
    fade-in: 20
    stay: 20
    fade-out: 20
  action-bar: "<white>Type /help for help."
  sound:
    key: entity.experience_orb.pickup
    # Available values: MASTER|MUSIC|RECORD|WEATHER|BLOCK|HOSTILE|NEUTRAL|PLAYER|AMBIENT|VOICE
    source: AMBIENT
    volume: 1.0
    # 0.0 - 2.0
    pitch: 2.0

# CREATE IN CODE
#  val feedbackYaml = mapOf<String, Any>(
#  "message" to "<red>Welcome to the server!",
#  "title" to mapOf<String, Any>(
#  "title" to "<red>Welcome to the server! (title)",
#  "sub-title" to "<dark_purple>We hope you'll like it here.",
#  "fade-in" to 20,
#  "stay" to 20,
#  "fade-out" to 20
#  ),
#  "action-bar" to "<white>Type /help for help.",
#  "sound" to mapOf<String, Any>(
#  "key" to "entity.experience_orb.pickup",
#  "source" to "AMBIENT",
#  "volume" to 1.0,
#  "pitch" to 2.0
#  )
#  )